import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button } from "../component/Button/Button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          columnGap: "10px",
          padding: "30px",
          backgroundColor: "rgba(35,48,61)",
          marginTop: "10px",
        }}
      >
        <Button text="TEXT" style="small" />
        <Button text="CONTAINED" style="lg--light" />
        <Button text="OUTLINED" style="lg--dark" />
      </div>
    </div>
  );
}
